/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mike/catkin_ws/src/wrock/srv/inverse_d.srv
 *
 */


#ifndef WROCK_MESSAGE_INVERSE_D_H
#define WROCK_MESSAGE_INVERSE_D_H

#include <ros/service_traits.h>


#include <wrock/inverse_dRequest.h>
#include <wrock/inverse_dResponse.h>


namespace wrock
{

struct inverse_d
{

typedef inverse_dRequest Request;
typedef inverse_dResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct inverse_d
} // namespace wrock


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wrock::inverse_d > {
  static const char* value()
  {
    return "6873795dc2f218e6b937d13b0214e87f";
  }

  static const char* value(const ::wrock::inverse_d&) { return value(); }
};

template<>
struct DataType< ::wrock::inverse_d > {
  static const char* value()
  {
    return "wrock/inverse_d";
  }

  static const char* value(const ::wrock::inverse_d&) { return value(); }
};


// service_traits::MD5Sum< ::wrock::inverse_dRequest> should match 
// service_traits::MD5Sum< ::wrock::inverse_d > 
template<>
struct MD5Sum< ::wrock::inverse_dRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wrock::inverse_d >::value();
  }
  static const char* value(const ::wrock::inverse_dRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wrock::inverse_dRequest> should match 
// service_traits::DataType< ::wrock::inverse_d > 
template<>
struct DataType< ::wrock::inverse_dRequest>
{
  static const char* value()
  {
    return DataType< ::wrock::inverse_d >::value();
  }
  static const char* value(const ::wrock::inverse_dRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wrock::inverse_dResponse> should match 
// service_traits::MD5Sum< ::wrock::inverse_d > 
template<>
struct MD5Sum< ::wrock::inverse_dResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wrock::inverse_d >::value();
  }
  static const char* value(const ::wrock::inverse_dResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wrock::inverse_dResponse> should match 
// service_traits::DataType< ::wrock::inverse_d > 
template<>
struct DataType< ::wrock::inverse_dResponse>
{
  static const char* value()
  {
    return DataType< ::wrock::inverse_d >::value();
  }
  static const char* value(const ::wrock::inverse_dResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WROCK_MESSAGE_INVERSE_D_H
