/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/mike/catkin_ws/src/wrock/srv/laser_scan.srv
 *
 */


#ifndef WROCK_MESSAGE_LASER_SCAN_H
#define WROCK_MESSAGE_LASER_SCAN_H

#include <ros/service_traits.h>


#include <wrock/laser_scanRequest.h>
#include <wrock/laser_scanResponse.h>


namespace wrock
{

struct laser_scan
{

typedef laser_scanRequest Request;
typedef laser_scanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct laser_scan
} // namespace wrock


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::wrock::laser_scan > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::wrock::laser_scan&) { return value(); }
};

template<>
struct DataType< ::wrock::laser_scan > {
  static const char* value()
  {
    return "wrock/laser_scan";
  }

  static const char* value(const ::wrock::laser_scan&) { return value(); }
};


// service_traits::MD5Sum< ::wrock::laser_scanRequest> should match 
// service_traits::MD5Sum< ::wrock::laser_scan > 
template<>
struct MD5Sum< ::wrock::laser_scanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::wrock::laser_scan >::value();
  }
  static const char* value(const ::wrock::laser_scanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::wrock::laser_scanRequest> should match 
// service_traits::DataType< ::wrock::laser_scan > 
template<>
struct DataType< ::wrock::laser_scanRequest>
{
  static const char* value()
  {
    return DataType< ::wrock::laser_scan >::value();
  }
  static const char* value(const ::wrock::laser_scanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::wrock::laser_scanResponse> should match 
// service_traits::MD5Sum< ::wrock::laser_scan > 
template<>
struct MD5Sum< ::wrock::laser_scanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::wrock::laser_scan >::value();
  }
  static const char* value(const ::wrock::laser_scanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::wrock::laser_scanResponse> should match 
// service_traits::DataType< ::wrock::laser_scan > 
template<>
struct DataType< ::wrock::laser_scanResponse>
{
  static const char* value()
  {
    return DataType< ::wrock::laser_scan >::value();
  }
  static const char* value(const ::wrock::laser_scanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WROCK_MESSAGE_LASER_SCAN_H
